version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: decorator
    versions:
    - 5.0.5
    - 5.0.6
  - dependency-name: matplotlib
    versions:
    - 3.4.0
  - dependency-name: scipy
    versions:
    - 1.6.0
    - 1.6.2
  - dependency-name: pillow
    versions:
    - 8.1.1
  - dependency-name: opencv-python
    versions:
    - 4.5.1.48
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
